blog/urls.py
from django.urls import path
from . import views
from .views import PostListView, MyPostListView, MyDeletedPostListView, BookmarkPostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeactivateView, \
    UsersListView, UserView, UserPostListView, PostsByCategory, PostsByTag, PostsByDate, vote, bookmark, ajax_form, send_email, subscribe_newsletter

urlpatterns = [
    path('', PostListView.as_view(), name='home'),
    path('posts/', MyPostListView.as_view(), name='posts'),
    path('deleted-posts/', MyDeletedPostListView.as_view(), name='posts_deleted'),
    path('bookmarks/', BookmarkPostListView.as_view(), name='bookmarks'),
    path('category=<slug:category>', PostsByCategory.as_view(), name='post_by_category'),
    path('tag=<slug:tag>', PostsByTag.as_view(), name='post_by_tag'),
    path('date/<int:year>/<int:month>', PostsByDate.as_view(), name='post_by_date'),
    path('user/<str:username>/', UserPostListView.as_view(), name='user_posts'),

    path('posts/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('posts/new/', PostCreateView.as_view(), name='post_new'),
    path('posts/<int:pk>/update/', PostUpdateView.as_view(), name='post_update'),
    path('posts/<int:pk>/deactivate/', PostDeactivateView.as_view(), name='post_deactivate'),
    
    path('ajax_form/', ajax_form, name="ajax_form"),
    path('vote/<int:pk>/<slug:slug>', vote, name="vote"),
    path('bookmark/<int:pk>', bookmark, name="bookmark"),

    path('profile/users/', UsersListView.as_view(), name='users'),
    path('profile/<str:slug>/', UserView.as_view(), name='user_profile'),
    
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('send-email/', send_email, name='send_email'),
    path('subscribe-newsletter/', subscribe_newsletter, name='subscribe_newsletter')
]

blogApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from users import views as user_views
from errors.views import error_400, error_403, error_404, error_500

handler400 = error_400
handler403 = error_403
handler404 = error_404
handler500 = error_500

urlpatterns = [
    path('admin/', admin.site.urls),    
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', 
        auth_views.PasswordResetView.as_view(
            template_name='users/password_reset.html'
        ), 
        name='password_reset'),
    path('password-reset/done/', 
        auth_views.PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ), 
        name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', 
        auth_views.PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'
        ), 
        name='password_reset_confirm'),
    path('password-reset-complete/', 
        auth_views.PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ), 
        name='password_reset_complete'),

    path('', include(('blog.urls', 'blog'), namespace="blog")),
    path('messenger/', include(('messenger.urls', 'messenger'), namespace="messenger")),
    path('notifications/', include(('notifications.urls', 'notifications'), namespace="notifications")),

    path('summernote/', include('django_summernote.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

messenger/urls.py
from django.urls import path
from .views import Messenger, thread, add_message, start_thread, new_thread, check_updates

urlpatterns = [
    path('', Messenger.as_view(), name='messenger'),
    path('thread/add', add_message, name='add'),
    path('thread/start-thread/', start_thread, name='start_thread'),
    path('thread/new-thread/', new_thread, name='new_thread'),

    path('thread/check-updates', check_updates, name='check-updates'),
    path('thread/', thread, name='thread'),
]

messenger/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import m2m_changed
from django.utils.dateformat import format

class ThreadManager(models.Manager):
    def find(self, user1, user2):
        # self = Thread.objects.all()
        queryset = self.filter(users=user1).filter(users=user2)
        
        if len(queryset) > 0:
            return queryset[0]

        return None

    def find_or_create(self, user1, user2):
        thread = self.find(user1, user2)

        if thread is None:
            thread = Thread.objects.create()
            thread.users.add(user1, user2)
            
        return thread

    def last_thread(self, user):
        try:
            return user.threads.latest('updated_at')           
        except Thread.DoesNotExist:
            return None

    def thread_last_update(self, user):
        last_thread = self.last_thread(user)
        if last_thread:
            return format(last_thread.updated_at, 'U')
        else:
            return 0


class Thread(models.Model):
    users = models.ManyToManyField(User, related_name='threads')    
    updated_at = models.DateTimeField(auto_now=True)
    objects = ThreadManager()

    class Meta:
        ordering = ['-updated_at']

class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    thread = models.ForeignKey(Thread, on_delete=models.CASCADE, related_name='messages')
    content = models.TextField()
    read = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['created_at']


"""def messages_changed(sender, **kwargs):
    instance = kwargs.pop("instance", None)
    action = kwargs.pop("action", None)
    pk_set = kwargs.pop("pk_set", None)

    false_pk_set = set()
    if action=="pre_add":
        for msg_pk in pk_set:
            msg = Message.objects.get(pk=msg_pk)
            if msg.user not in instance.users.all():
                print("Ups, ({}) no forma parte del hilo".format(msg.user))
                false_pk_set.add(msg_pk)
            
    #Buscar los mensajes de false_pk_set que están en pk_set y borrarlos de pk_set
    pk_set.difference_update(false_pk_set)

    # Forzar la actualización de la relación haciendo un save
    instance.save()

m2m_changed.connect(messages_changed, sender=Thread.messages.through)"""

messenger/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic import TemplateView
from .models import Thread, Message
from django.http import Http404, JsonResponse
from django.core.exceptions import PermissionDenied
from django.contrib.auth.models import User

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from users.mixins import AuthorCheckMixin
from django.utils.dateformat import format
from django.db.models import F, Max, Count, Sum
from django.db.models.functions import Concat
from django.db.models import CharField, Value, Subquery, OuterRef

from django.http import HttpResponseRedirect

from django.template.loader import render_to_string
import json

@method_decorator(login_required, name="dispatch")
class Messenger(TemplateView):
    template_name = "messenger/messenger.html"
    
    def get_context_data(self, **kwargs):
        new_thread = self.request.session.get('new_thread', None)
        redirect_thread = self.request.session.get('redirect_thread', None)
        self.request.session['new_thread'] = None
        self.request.session['redirect_thread'] = None
        context = super(Messenger, self).get_context_data(**kwargs)        
        context['last_update'] = Thread.objects.thread_last_update(self.request.user)
        context['new_thread'] = new_thread
        context['redirect_thread'] = redirect_thread
        context['thread_id'] = ''

        return context

    def post(self, *args, **kwargs):        
        user_id = self.request.POST.get('user_id')
        redirect_thread = self.request.POST.get('redirect_thread')
        if user_id:
            self.request.session['new_thread'] = user_id
        elif redirect_thread:
            self.request.session['redirect_thread'] = redirect_thread

        return redirect(reverse_lazy('messenger:messenger'))


@method_decorator(login_required, name="dispatch")
class ThreadDetail(DetailView):
    model = Thread

    def get_object(self):
        obj = super(ThreadDetail, self).get_object()
        if self.request.user not in obj.users.all():
            raise PermissionDenied()
        
        return obj

def add_message(request):
    json_response = {
        'success': False,
        'first': False
    }
    if request.user.is_authenticated:
        data = json.loads(request.body.decode("utf-8"))    
        thread_id = data['thread_id']
        content = data['content']
        if content:
            thread = get_object_or_404(Thread, pk=thread_id)
            message = Message.objects.create(thread=thread, user=request.user, content=content)
            thread.save()
            last_update = format(thread.updated_at, 'U')
            json_response['success'] = True
            json_response['created_at'] = message.created_at.strftime("%b. %d, %Y, %I:%M %p")
            total = thread.messages.count()
            if thread.messages.count()==1:
                json_response['first'] = True
                html_list = render_to_string('messenger/partials/thread_list.html', {'user': request.user, 'last_update': last_update})
                json_response['html_list'] = html_list

            json_response['total'] = total
            json_response['last_update'] = last_update
    else:
        raise "User is not authenticated"

    return JsonResponse(json_response)

def check_updates(request):
    json_response = {'update': False, 'update_list': False}
    if request.user.is_authenticated:
        data = json.loads(request.body.decode("utf-8"))
        thread_id = data['thread_id']
        last_update = data['last_update']

        last_thread = Thread.objects.last_thread(request.user)

        if last_thread:
            current_last_update = format(last_thread.updated_at, 'U')        
            json_response['current_last_update'] = current_last_update
            json_response['last_update'] = last_update

            if last_update!=current_last_update:
                json_response['update_list'] = True
                html_list = render_to_string('messenger/partials/thread_list.html', {'user': request.user, 'last_update': current_last_update, 'thread_id': thread_id})
                json_response['html_list'] = html_list
                json_response['thread_id'] = thread_id
                json_response['last_thread_id'] = last_thread.id

                if thread_id and thread_id==last_thread.id:                
                    json_response['update'] = True
                    html = render_to_string('messenger/partials/thread_messages.html', {'thread': last_thread, 'user': request.user})
                    json_response['html'] = html                                
    else:
        raise "User is not authenticated"

    return JsonResponse(json_response)

def thread(request):
    json_response = {'success': False}

    if request.user.is_authenticated:
        data = json.loads(request.body.decode("utf-8"))
        thread_id = data['thread_id']
        thread = get_object_or_404(Thread, pk=thread_id)
        json_response['success'] = True
        html = render_to_string('messenger/partials/thread_messages.html', {'thread': thread, 'user': request.user})
        updated = thread.messages.filter(read=False).exclude(user=request.user).update(read=True)
        json_response['read'] = (updated > 0)
        json_response['html'] = html
        json_response['new'] = (thread.messages.count()==0)
    else:
        raise "User is not authenticated"

    return JsonResponse(json_response)

@login_required
def start_thread(request):    
    json_response = {
        'success': False, 
        'new': False
    }
    if request.user.is_authenticated:
        data = json.loads(request.body.decode("utf-8"))
        user_id = data['user_id']
        user = get_object_or_404(User, pk=user_id)
        thread = Thread.objects.find_or_create(user, request.user)
        json_response['success'] = True                
        json_response['thread_id'] = thread.pk

        if thread.messages.count()==0:
            json_response['new'] = True
            json_response['last_update'] = Thread.objects.thread_last_update(request.user)

    else:
        raise "User is not authenticated"

    return JsonResponse(json_response)

@login_required
def new_thread(request):    
    json_response = {'success': False}
    if request.user.is_authenticated:
        users = User.objects.exclude(pk=request.user.pk)
        
        html = render_to_string('messenger/partials/new_thread_list.html', {'users': users})

        json_response['success'] = True                        
        json_response['html'] = html
    else:
        raise "User is not authenticated"

    return JsonResponse(json_response)

messenger/templates/messenger/messenger.html
{% extends 'blog/base/base.html' %}

{% load static %}

{% block content %}
    <div class="messenger clearfix">
        <div class="chat-screen">
            
            <div class="col-md-4 lateral-chat" id="lateral-chat">
                <div class="people-list js-fullheight" id="people-list">
					
					<div id="chat-list" class="chat-list">					
						<div class="new-thread-container">
							<a href="#" id="new-thread">
								<span class="icon-message"></span>
							</a>
						</div>
						{% include 'messenger/partials/thread_list.html' %}

					</div>

                </div>        
			</div>
			
			<div class="col-md-8 chat-container send-back" id="chat-container">
				
				<div id="background" class="background">
					<div class="img d-flex align-self-stretch align-items-center js-fullheight" style="background-image:url(/static/blog/img/background.jpg);">
					</div>
				</div>

                <div id="chat" class="chat">
					<div id="chat-detail" class="chat-detail"></div>                                        
                    <div class="chat-message clearfix">
                        <textarea name="message-to-send" class="form-control" id="message-to-send" placeholder="Escribe tu mensaje" rows="2"></textarea>                        
                        <button id="send" class="btn btn-primary btn-sm btn-disabled" data-thread-id="{{ thread_id }}">Enviar</button>
                    </div>
                
				</div>

				<div id="new-thread-list"></div>
            
            </div>

        </div>
    </div> 

{% endblock content %}


{% block extra_scripts %}

<script>
	
	(function() {

		const thread_detail_url = "{% url 'messenger:thread' %}"
		const add_message_url = "{% url 'messenger:add' %}"
		const check_updates_url = "{% url 'messenger:check-updates' %}"
		const start_thread_url = "{% url 'messenger:start_thread' %}"
		const new_thread_url = "{% url 'messenger:new_thread' %}"
		const send_btn = document.getElementById("send");
		const new_thread = document.getElementById("new-thread");
		const content_input = document.getElementById("message-to-send");
		const start_new_thread = Number("{{ new_thread }}")
		const redirect_thread = Number("{{ redirect_thread }}")		

		if(start_new_thread) {
			startThread(start_new_thread)
		}
		
		if(redirect_thread) {
			threadDetail(redirect_thread)
		}

		function ScrollBottomInThread(){
			const thread = document.getElementById("thread")
			thread.scrollTop = thread.scrollHeight
		}

		function addBackEvent(){
			const thread_back_btn = document.getElementById("thread-back")
			thread_back_btn.addEventListener("click", function() {
				document.getElementById('send').setAttribute('data-thread-id', 0)
				document.getElementById("lateral-chat").classList.remove("send-back")
				document.getElementById("chat-container").classList.add("send-back")
				document.getElementById("chat").style.display = "none"
				document.getElementById("background").classList.remove("hidden")
				document.getElementById("new-thread-list").style.display = "block"
				document.querySelectorAll(".active-chat").forEach(el=>el.classList.remove("active-chat"))
			})
		
		}

		function addEvents() {
			const thread_btn = document.querySelectorAll(".thread-list")			
			thread_btn.forEach(function(element) {	
				element.addEventListener('click', event => {
					const thread_id = element.getAttribute('data-thread-id')
					document.getElementById('send').setAttribute('data-thread-id', thread_id)
					threadDetail(Number(thread_id))
				})
			})	
		}
		
		function addStartThreadEvents() {
			const start_thread_btn = document.querySelectorAll(".start-thread-btn")
			const new_thread_back_btn = document.getElementById("new-thread-back")
			new_thread_back_btn.addEventListener("click", function() {				
				document.getElementById("new-thread").style.display = "block"
				document.getElementById("chat-container").classList.add("send-back")
				document.getElementById("new-thread-list").style.display = "none"
				document.getElementById("lateral-chat").classList.remove("send-back")
				document.getElementById("background").classList.add("hidden")
			})
			console.log(start_thread_btn)
			start_thread_btn.forEach(function(element) {
				console.log(element)
				element.addEventListener('click', event => {
					console.log(element)
					event.preventDefault()
					const user_id = element.getAttribute('data-user-id')				
					startThread(Number(user_id))
				})
			})
		}

		function threadDetail(thread_id) {
			fetch(thread_detail_url, {
				credentials: 'include',
				method: 'POST',
				headers: {
					"X-CSRFToken": getCookie("csrftoken"),
					"Accept": "application/json",
					"Content-Type": "application/json"
				},
				body: JSON.stringify({
					"thread_id": thread_id
				})
			}).then(
				response => response.json()
			).then(function(data) {
				if(data.success) {
					document.getElementById("new-thread").style.display = "block"
					document.getElementById("lateral-chat").classList.add("send-back")
					document.getElementById("chat-container").classList.remove("send-back")
					updateHtml("chat-detail", data.html)
					document.getElementById("chat").style.display = "block"
					document.getElementById("background").classList.add("hidden")
					document.getElementById("new-thread-list").style.display = "none"
					document.querySelectorAll(".active-chat").forEach(el=>el.classList.remove("active-chat"))
					if(!data.new) {
						const thread_list = document.querySelector("#thread_" + thread_id)
						thread_list.classList.add("active-chat")
						if(data.read) {
							thread_list.classList.remove("has-notifications")
							const badges = thread_list.getElementsByClassName("messenger-notifications")						
							badges[0].classList.add("d-none")
						}
						ScrollBottomInThread()
					}	
					addBackEvent()								
				}				
			})
		}

		function addMessage() {			
			const thread_id = document.getElementById('send').getAttribute('data-thread-id')
			const content = content_input.value

			content_input.value = ''
			send_btn.classList.add("btn-disabled")

			fetch(add_message_url, {
				credentials: 'include',
				method: 'POST',
				headers: {
					"X-CSRFToken": getCookie("csrftoken"),
					"Accept": "application/json",
					"Content-Type": "application/json"
				},
				body: JSON.stringify({
					"thread_id": thread_id, 
					"content": content
				})
			}).then(
				response => response.json()
			).then(function(data) {
				if(data.success){
					if (data.first){
						updateHtml("chat-list", data.html_list)
					}
					const message = document.createElement("li")					
					message.innerHTML = '<div class="message-data"><span class="message-data-name"><i class="fa fa-circle online"></i> Me</span><span class="message-data-time">' + formatDatetime(data.created_at) + '</span></div><div class="message my-message">' + decodeURIComponent(content) + '</div>'
					document.getElementById("thread-list").appendChild(message)
					document.getElementById("messages-count").innerHTML = data.total
					const thread_list = document.querySelector("#thread_" + thread_id)
					const last_message = thread_list.querySelector(".last-message")
					const last_time_message = thread_list.querySelector(".last-time-message")
					last_message.innerHTML = string_trunc(content)
					last_time_message.innerHTML = formatDate(data.created_at)
					document.getElementById("last-update").setAttribute('value', data.last_update)

					ScrollBottomInThread()
				}else{
					alert("Something weng wrong...")
				}
			})
		}

		new_thread.addEventListener("click", function() {
			fetch(new_thread_url, {
				credentials: 'include',
				method: 'POST',
				headers: {
					"X-CSRFToken": getCookie("csrftoken"),
					"Accept": "application/json",
					"Content-Type": "application/json"
				}
			}).then(
				response => response.json()
			).then(function(data) {
				if(data.success) {
					document.getElementById("lateral-chat").classList.add("send-back")
					document.getElementById("chat-container").classList.remove("send-back")
					document.getElementById("chat").style.display = "none"
					document.querySelectorAll(".active-chat").forEach(el=>el.classList.remove("active-chat"))
					document.getElementById("background").classList.add("hidden")
					updateHtml("new-thread-list", data.html)
					document.getElementById("new-thread").style.display = "none"
					document.getElementById("new-thread-list").style.display = "block"
					addStartThreadEvents()
				} else {
					alert("Something weng wrong...")
				}
			})
		})

		send_btn.addEventListener("click", function() {
			const content = content_input.value
			if(content.length > 0){				
				addMessage()				
			}
		})

		content_input.addEventListener("keyup", function(e){            
			if(!this.checkValidity() || !this.value){
			    send_btn.classList.add("btn-disabled")
			}else{
                send_btn.classList.remove("btn-disabled")
                if(e.keyCode==13){
                    send_btn.click()
                }
			}
		});		

		function updateHtml(selector, html) {
			const element = document.getElementById(selector)
			while(element.firstChild) {
				element.firstChild.remove()
			}
			element.innerHTML = html
		}
		
		function checkUpdates() {		
			const thread_id = document.getElementById('send').getAttribute('data-thread-id')
			const last_update = document.getElementById("last-update").value

			fetch(check_updates_url, {
				credentials: 'include',
				method: 'POST',
				headers: {
					"X-CSRFToken": getCookie("csrftoken"),
					"Accept": "application/json",
					"Content-Type": "application/json"
				},
				body: JSON.stringify({
					"thread_id": Number(thread_id), 
					"last_update": last_update
				})
			}).then(
				response => response.json()
			).then(function(data) {
				if(data.update_list){
					updateHtml("chat-list", data.html_list)
					addEvents()
				}
				if(data.update){         
					updateHtml("chat-detail", data.html)
					ScrollBottomInThread()
				}
			})            
		}

		function startThread(user_id) {			
			fetch(start_thread_url, {
				credentials: 'include',
				method: 'POST',
				headers: {
					"X-CSRFToken": getCookie("csrftoken"),
					"Accept": "application/json",
					"Content-Type": "application/json"
				},
				body: JSON.stringify({
					"user_id": user_id
				})
			}).then(response => response.json()).then(function(data){
				if(data.success) {
					if(data.new) {
						document.getElementById("last-update").setAttribute('value', data.last_update)
					}
					threadDetail(data.thread_id)
					document.getElementById('send').setAttribute('data-thread-id', data.thread_id)
				}else{
					alert("Something weng wrong...")
				}
			})
		}
		
		addEvents()
		setInterval(checkUpdates, 3000)

	})()
	
</script>

{% endblock extra_scripts %}