blog/urls.py
from django.urls import path
from . import views
from .views import PostListView, MyPostListView, MyDeletedPostListView, BookmarkPostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeactivateView, \
    UsersListView, UserView, UserPostListView, PostsByCategory, PostsByTag, PostsByDate, vote, bookmark, ajax_form, send_email, subscribe_newsletter

urlpatterns = [
    path('', PostListView.as_view(), name='home'),
    path('posts/', MyPostListView.as_view(), name='posts'),
    path('deleted-posts/', MyDeletedPostListView.as_view(), name='posts_deleted'),
    path('bookmarks/', BookmarkPostListView.as_view(), name='bookmarks'),
    path('category=<slug:category>', PostsByCategory.as_view(), name='post_by_category'),
    path('tag=<slug:tag>', PostsByTag.as_view(), name='post_by_tag'),
    path('date/<int:year>/<int:month>', PostsByDate.as_view(), name='post_by_date'),
    path('user/<str:username>/', UserPostListView.as_view(), name='user_posts'),

    path('posts/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('posts/new/', PostCreateView.as_view(), name='post_new'),
    path('posts/<int:pk>/update/', PostUpdateView.as_view(), name='post_update'),
    path('posts/<int:pk>/deactivate/', PostDeactivateView.as_view(), name='post_deactivate'),
    
    path('ajax_form/', ajax_form, name="ajax_form"),
    path('vote/<int:pk>/<slug:slug>', vote, name="vote"),
    path('bookmark/<int:pk>', bookmark, name="bookmark"),

    path('profile/users/', UsersListView.as_view(), name='users'),
    path('profile/<str:slug>/', UserView.as_view(), name='user_profile'),
    
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('send-email/', send_email, name='send_email'),
    path('subscribe-newsletter/', subscribe_newsletter, name='subscribe_newsletter')
]

blogApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from users import views as user_views
from errors.views import error_400, error_403, error_404, error_500

handler400 = error_400
handler403 = error_403
handler404 = error_404
handler500 = error_500

urlpatterns = [
    path('admin/', admin.site.urls),    
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', 
        auth_views.PasswordResetView.as_view(
            template_name='users/password_reset.html'
        ), 
        name='password_reset'),
    path('password-reset/done/', 
        auth_views.PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ), 
        name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', 
        auth_views.PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'
        ), 
        name='password_reset_confirm'),
    path('password-reset-complete/', 
        auth_views.PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ), 
        name='password_reset_complete'),

    path('', include(('blog.urls', 'blog'), namespace="blog")),
    path('messenger/', include(('messenger.urls', 'messenger'), namespace="messenger")),
    path('notifications/', include(('notifications.urls', 'notifications'), namespace="notifications")),

    path('summernote/', include('django_summernote.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/forms.py
from django import forms
from django.forms import ModelForm
from .models import Post
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'image', 'category', 'content', 'tags', 'is_active']
        labels = {
            'title': 'Título',
            'image': 'Imagen',
            'category': 'Categoría',
            'content': 'Contenido',
            'tags': 'Etiquetas',
            'is_active': 'Activo'
        }
        widgets = {
            'content': SummernoteWidget(),
        }

class CommentForm(forms.Form):
    parent_id = forms.CharField(widget=forms.HiddenInput(), required=False)
    name = forms.CharField(label='Name*', max_length=255, required=False)
    email = forms.EmailField(label='Email*', max_length=255, required=False)
    website = forms.CharField(max_length=255, required=False)
    content = forms.CharField(label='Message', widget=forms.Textarea(attrs={
        'rows': 4,
        'cols': 100
    }))

class ReplyForm(forms.Form):
    parent_id = forms.CharField(widget=forms.HiddenInput())
    content = forms.CharField(label='', widget=forms.Textarea(attrs={
        'rows': 4,
        'cols': 100
    }))

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import Http404
from .models import Post, Comment, Vote, Bookmark
from .forms import PostForm, CommentForm, ReplyForm
from django import forms
from django.contrib import messages
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.http import JsonResponse, HttpResponse
from django.core.exceptions import ObjectDoesNotExist
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, View, TemplateView
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from .utils import api_response
import time
import json
from .constants import contact_template_slug, newsletter_template_slug, email_sender_url, email_sender_api_key

from .signals import add_view
import urllib3

class BaseListView(ListView):
    template_name = 'blog/home.html'
    model = Post
    context_object_name = 'obj'
    ordering = ['-created_at']
    paginate_by = 10

    def get(self, request, *args, **kwargs):
        self.object_list = self.get_queryset()
        context = self.get_context_data()
        list_type = request.session.get('list_type', 0)
        context['list_type'] = list_type
        return render(self.request, 'blog/home.html', context)

    def post(self, *args, **kwargs):
        list_type = self.request.POST.get('list')
        self.request.session['list_type'] = list_type
        return redirect(reverse_lazy('blog:home'))


class PostListView(BaseListView):
    def get_queryset(self):
        search = self.request.GET.get('search')
        if search and search is not None:
            return Post.active.filter(
                Q(title__contains=search.strip()) | 
                Q(content__contains=search.strip())
            ).distinct().order_by('-created_at')

        return Post.active.all().order_by('-created_at')

class PostsByCategory(BaseListView):
    def get_queryset(self):
        return Post.active.filter(category__name=self.kwargs.get('category')).order_by('-created_at')
 
class PostsByTag(BaseListView):
    def get_queryset(self):
        return Post.active.filter(tags__name__in=[self.kwargs.get('tag')]).order_by('-created_at')

class PostsByDate(BaseListView):
    def get_queryset(self):
        month = self.kwargs.get('month')
        year = self.kwargs.get('year')            
        return Post.active.filter(created_at__year=year).filter(created_at__month=month).order_by('-created_at')

class UserPostListView(BaseListView):
    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.active.filter(author=user).order_by('-created_at')

@method_decorator(login_required, name='dispatch')
class BookmarkPostListView(BaseListView):
    def get_queryset(self):        
        bookmarks_ids = list(self.request.user.bookmarks.values_list('post_id', flat=True))
        return Post.active.filter(pk__in=bookmarks_ids).order_by('-created_at')

@method_decorator(login_required, name='dispatch')
class MyPostListView(BaseListView):
    def get_queryset(self):        
        return self.request.user.posts.filter(is_active=True).order_by('-created_at')

@method_decorator(login_required, name='dispatch')
class MyDeletedPostListView(BaseListView):
    def get_queryset(self):        
        return self.request.user.posts.filter(is_active=False).order_by('-created_at')

class PostDetailView(DetailView):
    def get(self, *args, **kwargs):
        comment_id = self.request.GET.get('comment_id')
        post = get_object_or_404(Post, pk=self.kwargs.get('pk'))        
        comments = post.comments.filter(active=True, parent=None).order_by('-created_at')
        form = CommentForm()

        if self.request.user.is_authenticated:
            form.fields['name'].widget = forms.HiddenInput()
            form.fields['email'].widget = forms.HiddenInput()
            form.fields['website'].widget = forms.HiddenInput()
            form.fields['content'].label = ''

        context = {'post': post, 'comments': comments, 'form': form, 'comment_id': comment_id}

        add_view.send(sender=Post, user=self.request.user, post=post)

        return render(self.request, "blog/post_detail.html", context)
    
    def post(self, *args, **kwargs):
        form = CommentForm(self.request.POST or None)
        if form.is_valid():
            pk = self.kwargs.get('pk')
            post = get_object_or_404(Post, pk=pk)
            name = form.cleaned_data.get("name")
            email = form.cleaned_data.get("email")
            website = form.cleaned_data.get("website")
            content = form.cleaned_data.get("content")
            parent_id = form.cleaned_data.get("parent_id")

            if content:
                if self.request.user.is_authenticated:                
                    comment = Comment(
                        content=content,
                        author=self.request.user,
                        post=post
                    )
                else:
                    comment = Comment(
                        content=content,
                        name=name,
                        email=email,
                        website=website,
                        post=post
                    )

                if parent_id:
                    parent_comment = Comment.objects.get(pk=parent_id)
                    comment.parent = parent_comment
                    
                comment.save()
                return redirect('blog:post_detail', pk=pk)
            else:
                messages.info(self.request, "Please write some comment.")
                return redirect('blog:post_detail', pk=pk)

@method_decorator(login_required, name='dispatch')
class UsersListView(ListView):
    template_name = 'blog/users.html'
    model = User
    context_object_name = 'obj'
    ordering = ['username']
    paginate_by = 12

    def get_queryset(self):
        return User.objects.filter(profile__is_public=True).exclude(pk=self.request.user.pk).order_by('username')

@method_decorator(login_required, name='dispatch')
class UserView(UserPassesTestMixin, DetailView):
    slug_field = "username"
    model = User
    template_name = 'blog/user_profile.html'
    context_object_name = 'obj'
    
    def handle_no_permission(self):
        return redirect('profile')

    def test_func(self):
        user = self.get_object()        
        if self.request.user==self.get_object():            
            return False
        if user.profile.is_public is False:
            raise Http404
        return True

    def get_context_data(self, **kwargs):
        context = super(UserView, self).get_context_data(**kwargs)
        context['posts'] = self.object.posts.filter(is_active=True).order_by('-created_at')[:4]
        return context

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    # fields = ['image', 'category', 'title', 'content', 'is_active']    
    form_class = PostForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    form_class = PostForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False
            
class PostDeactivateView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post

    def get(self, *args, **kwargs):
        raise Http404
    
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = '/'
        if self.object.author == self.request.user:
            self.object.is_active=(not self.object.is_active)
            self.object.save()
            success_url = '/posts' if self.object.is_active else '/deleted-posts'

        return redirect(success_url)
 
def about(request):
    template_name = 'blog/about.html'
    return render(request, template_name, {'title': 'About'})

def contact(request):
    template_name = 'blog/contact.html'
    return render(request, template_name, {'title': 'Contact'})

""" AJAX """


def send_email(request):
    json_response = {'success': False}

    http = urllib3.PoolManager()

    data = json.loads(request.body.decode("utf-8"))

    if('subject' not in data): 
        json_response['msg'] = 'El campo \'subject\' no puede estar vacío' 
        return api_response(json_response)
    elif('email' not in data): 
        json_response['msg'] = 'El campo \'email\' no puede estar vacío' 
        return api_response(json_response)
    elif('content' not in data): 
        json_response['msg'] = 'El campo \'content\' no puede estar vacío' 
        return api_response(json_response)

    name = data['name']
    email = data['email']
    subject = data['subject']
    content = data['content']

    attempt_num = 0
    while attempt_num < 1:       
        body = {'name': name, 'from': email, 'subject': subject, 'content': content, 'template_slug': contact_template_slug, 'type': 'contact'}
        headers = {'Content-Type': 'application/json', 'api-key': email_sender_api_key}
        response = http.request(
            'POST',
            email_sender_url,
            body=json.dumps(body),
            headers=headers
        )
        if response.status == 200:
            data = json.loads(response.data.decode('utf-8'))
            return JsonResponse(data)
        else:

blogApp/blog/templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="{%  static 'blog/img/icon.ico' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
    
    <!-- Main CSS -->
    <link rel="stylesheet" href="{% static 'blog/css/main.css' %}">

    {% if title %}
        <title>Blog! - {{ title }}</title>
    {% else %}
        <title>Blog!</title>
    {% endif %}

  </head>
  <body>

    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container">
                    <a class="navbar-brand mr-4" href="{% url 'blog:home' %}">Blog</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <div class="navbar-nav mr-auto">
                        <a class="nav-item nav-link" href="{% url 'blog:home' %}">Home</a>
                        <a class="nav-item nav-link" href="{% url 'blog:about' %}">About</a>
                    </div>
                    
                    {% if user.is_authenticated %}
                        <div class="navbar-nav">
                            <a class="nav-item nav-link" href="{% url 'blog:post_new' %}">New Post</a>
                            <a class="nav-item nav-link" href="{% url 'blog:user_posts' user.username %}">My Posts</a>
                            <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                            <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                        </div>
                    {% else %}
                        <div class="navbar-nav">
                            <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                            <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
                        </div>                
                    {% endif %}
                </div>
            </div>
        </nav>
    </header>
    
    <main role="main" class="container">
        <div class="row justify-content-md-center">
            <div class="col-md-8">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}

                {% block content %}{% endblock %}
            </div>
            <div class="col-md-4">
                <div class="content-section">
                    <h3>Our Sidebar</h3>
                    <p class='text-muted'>You can put any information here you'd like.
                    <ul class="list-group">
                        <li class="list-group-item list-group-item-light">Latest Posts</li>
                        <li class="list-group-item list-group-item-light">Announcements</li>
                        <li class="list-group-item list-group-item-light">Calendars</li>
                        <li class="list-group-item list-group-item-light">etc</li>
                    </ul>
                    </p>
                </div>
            </div>
        </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'blog/js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'blog/js/popper.min.js' %}"></script>
    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>

    {% block control_modal %}
    <script>
      function message(msg, type='green'){
        $.alert({
          title: '',
          theme: 'material',
          type: type,
          content: msg
        });
      }
    </script>
    {% endblock control_modal %}

    {% block extra_scripts %}{% endblock extra_scripts %}
  </body>
</html>

blogApp/blog/templates/blog/comment_partial.html
{% load static %}

<li class="comment">
    <div class="vcard bio">
        {% if item.author %}
            <img src="{{ item.author.profile.image.url }}" alt="Profile">
        {% else %}
            <img src="{% static 'blog/img/default.jpg' %}" alt="Profile">
        {% endif %}
    </div>
    <div class="comment-body">

        {% if item.author %}
            <h3>{{ item.author }}</h3>
        {% else %}
            <h3>{{ item.name }} <span class="email">{{ item.email }}</span></h3>
            <span class="website">{{ item.website }}</span>
        {% endif %}

        <div class="meta">{{ item.created_at | date:'F d, Y' }}</div>
        
        <p>{{ item.content}}</p>

        <div class="votes">
            {% if user.is_authenticated %}
                <a href="#" class="btn vote_btn like" data-like="1" data-url="{% url 'blog:vote' item.id 'comment' %}" role="button">
                    <i class="icon-thumbs-o-up"></i> 
                    <span class="like_count">{{ item.get_likes }}</span>
                </a>
                <a href="#" class="btn vote_btn dislike" data-like="0" data-url="{% url 'blog:vote' item.id 'comment' %}" role="button">
                    <i class="icon-thumbs-o-down"></i> 
                    <span class="dislike_count">{{ item.get_dislikes }}</span>
                </a>
            {% else %}
                <i class="icon-thumbs-o-up"></i> 
                <span class="like_count mr-3">{{ item.get_likes }}</span>
                <i class="icon-thumbs-o-down"></i> 
                <span class="dislike_count mr-2">{{ item.get_dislikes }}</span>
            {% endif %}
            <a href="#" class="reply" data-id="{{ item.id }}" role="button">Reply</a>
        </div>
        <div class="reply_div"></div>
    </div>

    {%if item.replies.exists %}
        {%for reply in item.replies.all %}
            {%with item=reply template_name="blog/reply_partial.html" %}
                {%include template_name%}
            {%endwith%}
        {%endfor%}
    {%endif%}    
    
</li>

blogApp/blog/templates/blog/reply_partial.html
{% load static %}

<ul class="children">
  <li class="comment">
    <div class="vcard bio">
      {% if item.author %}
        <img src="{{ item.author.profile.image.url }}" alt="Profile">
      {% else %}
        <img src="{% static 'blog/img/default.jpg' %}" alt="Profile">
      {% endif %}
    </div>
    <div class="comment-body">
      
      {% if item.author %}
        <p>{{ item.author }}</p>
      {% else %}
        <h3>{{ item.name }} <span class="email">{{ item.email }}</span></h3>
        <span class="website">{{ item.website }}</span>
      {% endif %}

      <div class="meta">{{ item.created_at | date:'F d, Y' }}</div>

      <p>{{ item.content}}</p>
      
      <div class="votes">
        {% if user.is_authenticated %}
          <a href="#" class="btn vote_btn like" data-like="1" data-url="{% url 'blog:vote' item.id 'comment' %}" role="button">
            <i class="icon-thumbs-o-up"></i> 
            <span class="like_count">{{ item.get_likes }}</span>
          </a>
          <a href="#" class="btn vote_btn dislike" data-like="0" data-url="{% url 'blog:vote' item.id 'comment' %}" role="button">
            <i class="icon-thumbs-o-down"></i> 
            <span class="dislike_count">{{ item.get_dislikes }}</span>
          </a>
        {% else %}
          <i class="icon-thumbs-o-up"></i> 
          <span class="like_count mr-3">{{ item.get_likes }}</span>
          <i class="icon-thumbs-o-down"></i> 
          <span class="dislike_count mr-2">{{ item.get_dislikes }}</span>
        {% endif %}
        <a href="#" class="reply" data-id="{{ item.id }}" role="button">Reply</a>
      </div> 
      <div class="reply_div"></div>
    </div>

    {%if item.replies.exists %}
      {%for reply in item.replies.all %}
        {%with item=reply template_name="blog/reply_partial.html" %}
          {%include template_name%}
        {%endwith%}
      {%endfor%}
    {%endif%}    

  </li>
</ul>