blog/urls.py
from django.urls import path
from . import views
from .views import PostListView, MyPostListView, MyDeletedPostListView, BookmarkPostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeactivateView, \
    UsersListView, UserView, UserPostListView, PostsByCategory, PostsByTag, PostsByDate, vote, bookmark, ajax_form, send_email, subscribe_newsletter

urlpatterns = [
    path('', PostListView.as_view(), name='home'),
    path('posts/', MyPostListView.as_view(), name='posts'),
    path('deleted-posts/', MyDeletedPostListView.as_view(), name='posts_deleted'),
    path('bookmarks/', BookmarkPostListView.as_view(), name='bookmarks'),
    path('category=<slug:category>', PostsByCategory.as_view(), name='post_by_category'),
    path('tag=<slug:tag>', PostsByTag.as_view(), name='post_by_tag'),
    path('date/<int:year>/<int:month>', PostsByDate.as_view(), name='post_by_date'),
    path('user/<str:username>/', UserPostListView.as_view(), name='user_posts'),

    path('posts/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('posts/new/', PostCreateView.as_view(), name='post_new'),
    path('posts/<int:pk>/update/', PostUpdateView.as_view(), name='post_update'),
    path('posts/<int:pk>/deactivate/', PostDeactivateView.as_view(), name='post_deactivate'),
    
    path('ajax_form/', ajax_form, name="ajax_form"),
    path('vote/<int:pk>/<slug:slug>', vote, name="vote"),
    path('bookmark/<int:pk>', bookmark, name="bookmark"),

    path('profile/users/', UsersListView.as_view(), name='users'),
    path('profile/<str:slug>/', UserView.as_view(), name='user_profile'),
    
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('send-email/', send_email, name='send_email'),
    path('subscribe-newsletter/', subscribe_newsletter, name='subscribe_newsletter')
]

blogApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from users import views as user_views
from errors.views import error_400, error_403, error_404, error_500

handler400 = error_400
handler403 = error_403
handler404 = error_404
handler500 = error_500

urlpatterns = [
    path('admin/', admin.site.urls),    
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', 
        auth_views.PasswordResetView.as_view(
            template_name='users/password_reset.html'
        ), 
        name='password_reset'),
    path('password-reset/done/', 
        auth_views.PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ), 
        name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', 
        auth_views.PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'
        ), 
        name='password_reset_confirm'),
    path('password-reset-complete/', 
        auth_views.PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ), 
        name='password_reset_complete'),

    path('', include(('blog.urls', 'blog'), namespace="blog")),
    path('messenger/', include(('messenger.urls', 'messenger'), namespace="messenger")),
    path('notifications/', include(('notifications.urls', 'notifications'), namespace="notifications")),

    path('summernote/', include('django_summernote.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

messenger/urls.py
from django.urls import path
from .views import Messenger, thread, add_message, start_thread, new_thread, check_updates

urlpatterns = [
    path('', Messenger.as_view(), name='messenger'),
    path('thread/add', add_message, name='add'),
    path('thread/start-thread/', start_thread, name='start_thread'),
    path('thread/new-thread/', new_thread, name='new_thread'),

    path('thread/check-updates', check_updates, name='check-updates'),
    path('thread/', thread, name='thread'),
]

blog/forms.py
from django import forms
from django.forms import ModelForm
from .models import Post
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'image', 'category', 'content', 'tags', 'is_active']
        labels = {
            'title': 'Título',
            'image': 'Imagen',
            'category': 'Categoría',
            'content': 'Contenido',
            'tags': 'Etiquetas',
            'is_active': 'Activo'
        }
        widgets = {
            'content': SummernoteWidget(),
        }

class CommentForm(forms.Form):
    parent_id = forms.CharField(widget=forms.HiddenInput(), required=False)
    name = forms.CharField(label='Name*', max_length=255, required=False)
    email = forms.EmailField(label='Email*', max_length=255, required=False)
    website = forms.CharField(max_length=255, required=False)
    content = forms.CharField(label='Message', widget=forms.Textarea(attrs={
        'rows': 4,
        'cols': 100
    }))

class ReplyForm(forms.Form):
    parent_id = forms.CharField(widget=forms.HiddenInput())
    content = forms.CharField(label='', widget=forms.Textarea(attrs={
        'rows': 4,
        'cols': 100
    }))

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import Http404
from .models import Post, Comment, Vote, Bookmark
from .forms import PostForm, CommentForm, ReplyForm
from django import forms
from django.contrib import messages
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.http import JsonResponse, HttpResponse
from django.core.exceptions import ObjectDoesNotExist
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, View, TemplateView
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from .utils import api_response
import time
import json
from .constants import contact_template_slug, newsletter_template_slug, email_sender_url, email_sender_api_key

from .signals import add_view
import urllib3

class BaseListView(ListView):
    template_name = 'blog/home.html'
    model = Post
    context_object_name = 'obj'
    ordering = ['-created_at']
    paginate_by = 10

    def get(self, request, *args, **kwargs):
        self.object_list = self.get_queryset()
        context = self.get_context_data()
        list_type = request.session.get('list_type', 0)
        context['list_type'] = list_type
        return render(self.request, 'blog/home.html', context)

    def post(self, *args, **kwargs):
        list_type = self.request.POST.get('list')
        self.request.session['list_type'] = list_type
        return redirect(reverse_lazy('blog:home'))


class PostListView(BaseListView):
    def get_queryset(self):
        search = self.request.GET.get('search')
        if search and search is not None:
            return Post.active.filter(
                Q(title__contains=search.strip()) | 
                Q(content__contains=search.strip())
            ).distinct().order_by('-created_at')

        return Post.active.all().order_by('-created_at')

class PostsByCategory(BaseListView):
    def get_queryset(self):
        return Post.active.filter(category__name=self.kwargs.get('category')).order_by('-created_at')
 
class PostsByTag(BaseListView):
    def get_queryset(self):
        return Post.active.filter(tags__name__in=[self.kwargs.get('tag')]).order_by('-created_at')

class PostsByDate(BaseListView):
    def get_queryset(self):
        month = self.kwargs.get('month')
        year = self.kwargs.get('year')            
        return Post.active.filter(created_at__year=year).filter(created_at__month=month).order_by('-created_at')

class UserPostListView(BaseListView):
    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.active.filter(author=user).order_by('-created_at')

@method_decorator(login_required, name='dispatch')
class BookmarkPostListView(BaseListView):
    def get_queryset(self):        
        bookmarks_ids = list(self.request.user.bookmarks.values_list('post_id', flat=True))
        return Post.active.filter(pk__in=bookmarks_ids).order_by('-created_at')

@method_decorator(login_required, name='dispatch')
class MyPostListView(BaseListView):
    def get_queryset(self):        
        return self.request.user.posts.filter(is_active=True).order_by('-created_at')

@method_decorator(login_required, name='dispatch')
class MyDeletedPostListView(BaseListView):
    def get_queryset(self):        
        return self.request.user.posts.filter(is_active=False).order_by('-created_at')

class PostDetailView(DetailView):
    def get(self, *args, **kwargs):
        comment_id = self.request.GET.get('comment_id')
        post = get_object_or_404(Post, pk=self.kwargs.get('pk'))        
        comments = post.comments.filter(active=True, parent=None).order_by('-created_at')
        form = CommentForm()

        if self.request.user.is_authenticated:
            form.fields['name'].widget = forms.HiddenInput()
            form.fields['email'].widget = forms.HiddenInput()
            form.fields['website'].widget = forms.HiddenInput()
            form.fields['content'].label = ''

        context = {'post': post, 'comments': comments, 'form': form, 'comment_id': comment_id}

        add_view.send(sender=Post, user=self.request.user, post=post)

        return render(self.request, "blog/post_detail.html", context)
    
    def post(self, *args, **kwargs):
        form = CommentForm(self.request.POST or None)
        if form.is_valid():
            pk = self.kwargs.get('pk')
            post = get_object_or_404(Post, pk=pk)
            name = form.cleaned_data.get("name")
            email = form.cleaned_data.get("email")
            website = form.cleaned_data.get("website")
            content = form.cleaned_data.get("content")
            parent_id = form.cleaned_data.get("parent_id")

            if content:
                if self.request.user.is_authenticated:                
                    comment = Comment(
                        content=content,
                        author=self.request.user,
                        post=post
                    )
                else:
                    comment = Comment(
                        content=content,
                        name=name,
                        email=email,
                        website=website,
                        post=post
                    )

                if parent_id:
                    parent_comment = Comment.objects.get(pk=parent_id)
                    comment.parent = parent_comment
                    
                comment.save()
                return redirect('blog:post_detail', pk=pk)
            else:
                messages.info(self.request, "Please write some comment.")
                return redirect('blog:post_detail', pk=pk)

@method_decorator(login_required, name='dispatch')
class UsersListView(ListView):
    template_name = 'blog/users.html'
    model = User
    context_object_name = 'obj'
    ordering = ['username']
    paginate_by = 12

    def get_queryset(self):
        return User.objects.filter(profile__is_public=True).exclude(pk=self.request.user.pk).order_by('username')

@method_decorator(login_required, name='dispatch')
class UserView(UserPassesTestMixin, DetailView):
    slug_field = "username"
    model = User
    template_name = 'blog/user_profile.html'
    context_object_name = 'obj'
    
    def handle_no_permission(self):
        return redirect('profile')

    def test_func(self):
        user = self.get_object()        
        if self.request.user==self.get_object():            
            return False
        if user.profile.is_public is False:
            raise Http404
        return True

    def get_context_data(self, **kwargs):
        context = super(UserView, self).get_context_data(**kwargs)
        context['posts'] = self.object.posts.filter(is_active=True).order_by('-created_at')[:4]
        return context

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    # fields = ['image', 'category', 'title', 'content', 'is_active']    
    form_class = PostForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    form_class = PostForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False
            
class PostDeactivateView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post

    def get(self, *args, **kwargs):
        raise Http404
    
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = '/'
        if self.object.author == self.request.user:
            self.object.is_active=(not self.object.is_active)
            self.object.save()
            success_url = '/posts' if self.object.is_active else '/deleted-posts'

        return redirect(success_url)
 
def about(request):
    template_name = 'blog/about.html'
    return render(request, template_name, {'title': 'About'})

def contact(request):
    template_name = 'blog/contact.html'
    return render(request, template_name, {'title': 'Contact'})

""" AJAX """


def send_email(request):
    json_response = {'success': False}

    http = urllib3.PoolManager()

    data = json.loads(request.body.decode("utf-8"))

    if('subject' not in data): 
        json_response['msg'] = 'El campo \'subject\' no puede estar vacío' 
        return api_response(json_response)
    elif('email' not in data): 
        json_response['msg'] = 'El campo \'email\' no puede estar vacío' 
        return api_response(json_response)
    elif('content' not in data): 
        json_response['msg'] = 'El campo \'content\' no puede estar vacío' 
        return api_response(json_response)

    name = data['name']
    email = data['email']
    subject = data['subject']
    content = data['content']

    attempt_num = 0
    while attempt_num < 1:       
        body = {'name': name, 'from': email, 'subject': subject, 'content': content, 'template_slug': contact_template_slug, 'type': 'contact'}
        headers = {'Content-Type': 'application/json', 'api-key': email_sender_api_key}
        response = http.request(
            'POST',
            email_sender_url,
            body=json.dumps(body),
            headers=headers
        )
        if response.status == 200:
            data = json.loads(response.data.decode('utf-8'))
            return JsonResponse(data)
        else:

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
from django.urls import reverse_lazy


def register(request):
    template_name = 'users/register.html'
    
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Your account has been created!, You are now able to log in')
            new_user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password1'],
            )
            login(request, new_user)
            return redirect(reverse_lazy('blog:home'))
    else:
        form = UserRegisterForm()

    context = {'form': form}
    return render(request, template_name, context)

@login_required
def profile(request):
    template_name = 'users/profile.html'

    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user)
        profile_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect(reverse_lazy('blog:home'))
    else:
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.profile)
    
    context = {
        'user_form': user_form,
        'profile_form': profile_form,
    }
    
    return render(request, template_name, context)

blog/templates/blog/about.html
{% extends "blog/base/base.html" %}

{% block content %}

    <section class="ftco-about img ftco-section ftco-no-pt ftco-no-pb" id="about-section">
        <div class="container-fluid px-0">
            <div class="row d-flex">
                <div class="col-md-6 d-flex">
                    <div class="img d-flex align-self-stretch align-items-center js-fullheight" style="background-image:url(/static/blog/img/background.jpg);">
                    </div>
                </div>
                <div class="col-md-6 d-flex align-items-center">
                    <div class="text px-4 pt-5 pt-md-0 px-md-4 pr-md-5 ftco-animate">
                        <h2 class="mb-4">I'm a <span>Ñoño</span> Blogger &amp; Explorer</h2>
                        <p>A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

blog/templates/blog/post_detail.html
{% extends "blog/base/base.html" %}

{% load crispy_forms_tags %}


{% block content %}

    {% get_related_posts post as related_posts %}
    
    {% if user.is_authenticated %}
        {% get_post_bookmark post user as bookmark %}
    {% endif %}

    {% include 'blog/base/modals/confirmation-modal.html' %}

    <section class="ftco-section ftco-no-pt ftco-no-pb">

        <div class="row d-flex">

            <div id="post-detail" class="container col-xl-8 col-lg-12 col-md-12 col-sm-12 p-5">

                <div class="row pt-md-4">
                    <div class="post-category">
                        <p><a href="{% url 'blog:post_by_category' post.category.name %}"><em>{{ post.category }}</em></a></p>
                    </div>
                    <h1 class="post-title">
                        {{ post.title }}
                        {% if user.is_authenticated %}                            
                            <a href="#" class="btn bookmark-btn" data-url="{% url 'blog:bookmark' post.id %}" role="button">                                
                                <i class="icon {% if bookmark %}icon-heart{% else %}icon-heart-o{% endif %}"></i>
                            </a>
                        {% endif %}
                    </h1>   
                </div>                                        
                {% if post.author == user %}
                    <div class="float-right mb-4">
                        <a class="btn btn-outline-yellow btn-sm mt-1 mb-1" href="{% url 'blog:post_update' post.id %}">Editar</a>
                        {% if post.is_active %}                            
                            <a href="#" url="{% url 'blog:post_deactivate' post.id %}" class="btn btn-outline-danger btn-sm mt-1 mb-1 confirm-delete" title="Delete" data-toggle="modal" data-target="#confirmDeleteModal">Desechar</a>                            
                            {% else %}
                            <a href="#" url="{% url 'blog:post_deactivate' post.id %}" class="btn btn-outline-success btn-sm mt-1 mb-1 confirm-delete" title="Delete" data-toggle="modal" data-target="#confirmDeleteModal">Recuperar</a>                            
                        {% endif %}
                    </div>
                {% endif %}    
                {% if post.image %}
                    <div class="mt-4">
                        <p>
                            <img src="{{ post.image.url }}" alt="" class="img-fluid">
                        </p>
                    </div>
                {% endif %}
                
                <div class="pt-md-4 post-content">
                    <p>{{ post.content | safe }}</p>
                </div>                    

                <div class="votes row pt-2 mt-2">
                    {% if user.is_authenticated %}                            
                        <a href="#" class="btn vote_btn like" data-like="1" data-url="{% url 'blog:vote' post.id 'post' %}" role="button">
                            <i class="far fa-thumbs-up"></i> 
                            <span class="like_count">{{ post.get_likes }}</span>
                        </a>
                        <a href="#" class="btn vote_btn dislike" data-like="0" data-url="{% url 'blog:vote' post.id 'post' %}" role="button">
                            <i class="far fa-thumbs-down"></i> 
                            <span class="dislike_count">{{ post.get_dislikes }}</span>
                        </a>
                    {% else %}
                        <i class="far fa-thumbs-up"></i> 
                        <span class="like_count mr-3">{{ post.get_likes }}</span>
                        <i class="far fa-thumbs-down"></i> 
                        <span class="dislike_count mr-2">{{ post.get_dislikes }}</span>
                    {% endif %}
                </div>

                <div class="row mb-5 mt-5 justify-content-center">
                    <div class="tags">
                        {% for tag in post.tags.all %}
                            <a href="{% url 'blog:post_by_tag' tag.slug %}" class="tag-cloud-link">{{ tag }}</a>
                        {% endfor %}
                    </div>
                </div>                    


                <div class="pt-4 mt-4">
                    <div class="about-author profile d-flex pt-2 pb-2 col-lg-12">
                        <div class="bio col-4 col-md-2 p-1">
                            <img src="{{ post.author.profile.image.url }}" alt="Imagen" class="mb-4">
                        </div>
                        <div class="desc col-8 col-md-10 p-1">
                            <a href="{% url 'blog:user_profile' post.author %}"><h3>{{ post.author }}</h3></a>
                            <p>{{ post.author.profile.bio}}</p>
                        </div>
                    </div>
                </div>

                <div class="row pt-md-4">
                    <div class="pt-5 mt-5">
                        <h3 class="mb-5 font-weight-bold">Relacionados</h3>

                        {% for related in related_posts %}
                        <div class="block-21 mb-4 d-flex">
                            <a href="{% url 'blog:post_detail' related.id %}" class="blog-img mr-4" style="background-image: url('{{ related.image.url }}');"></a>
                            <div class="text">
                                <h3 class="heading"><a href="{% url 'blog:post_detail' related.id %}">{{ related.title }}</a></h3>
                                <div class="meta">
                                    <div><span class="fal fa-calendar-alt"></span> {{ related.created_at | date:'d F Y' }}</div>
                                </div>
                                <div class="meta">
                                    <div>
                                        <a href="{% url 'blog:user_posts' related.author %}">
                                            <span class="far fa-user"></span> {{ related.author }}
                                        </a>
                                    </div>
                                    <div><span class="far fa-comments"></span> {{ related.get_comments }}</div>
                                    <div><span class="far fa-thumbs-up"></span> {{ related.get_likes }}</div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>

                <div class="d-none" id="replyForm">
                    <article class="media comment content-section mt-3 active_reply">
                        <img class="rounded-circle comment-img" src="{{ request.user.profile.image.url }}" />
                        <div class="media-body col-lg-8">
                            <form method="POST">
                                {% csrf_token %}
                                {{ form | crispy }}
                                <button class="btn btn-primary mr-1 float-right" type="submit">Responder</button>
                            </form>
                        </div>
                    </article>
                </div>

                <div class="row pt-md-4">
                    <div class="pt-5 mt-5">
                        <h3 class="mb-5 font-weight-bold">{{ post.get_comments }} comment{{ post.get_comments | pluralize }}</h3>
                        <ul class="comment-list">
                            {% for item in comments.all %}
                                {% include "blog/partials/comment.html" %}
                            {% endfor %}
                        </ul>
                    
                        <div class="comment-form-wrap pt-5">                                
                            <h4 class="article-title">Escribe un Comentario</h4>
                            {% if user.is_authenticated %}                                    
                                <article class="media comment content-section mt-3">
                                    <img class="comment-img" src="{{ request.user.profile.image.url }}" />
                                    <div class="media-body">
                                        <form method="POST">
                                            {% csrf_token %}
                                            {{ form | crispy }}
                                            <button class="btn btn-yellow mr-1 float-right" type="submit">Comentar</button>
                                        </form>
                                    </div>
                                </article>
                            {% else %}
                                <form method="POST">
                                    {% csrf_token %}
                                    {{ form | crispy }}
                                    <button class="btn btn-yellow mr-1 float-right" type="submit">Comentar</button>
                                </form>
                            {% endif %}
                        </div>
                    </div>

                </div>

            </div>
                
            {% include "blog/base/sidebar.html" %}

        </div>

    </section>
                
{% endblock content %}


{% block extra_scripts %}
    <script>
        $(document).ready(function(){

            const deactivate_btn = document.querySelectorAll('.confirm-delete')
            
            deactivate_btn.forEach(element => element.addEventListener('click', event => {
                event.preventDefault()
                const element = event.target
                const url = element.getAttribute('url')
                document.getElementById('confirmDeleteModalForm').setAttribute('action', url)
            }))

            const comment_id = "{{ comment_id }}";

            function scrollToCenter(id) {
                const scrollTo = $("#comment_" + id)
                
                $('html, body').animate({
                    scrollTop: $(scrollTo).offset().top                    
                }, 700);

                const comment_content = $(scrollTo).find(".comment-content:first")
                const comment_username = $(scrollTo).find("h3:first")
                const comment_meta = $(scrollTo).find(".meta:first")
                $(comment_content).css("color", "green")
                $(comment_meta).css("color", "green")
                $(comment_username).css("color", "green")
            }
            
            if(comment_id!="None"){
                id = JSON.parse(comment_id)
                scrollToCenter(id)
            }
            
            $(".vote_btn").click(function(e){
                e.preventDefault();

                var element =$(this);
                var like = $(element).data("like");
                var url = $(element).data("url");

                $.ajax({
                    type: "POST",
                    url: url,            
                    data: {csrfmiddlewaretoken: "{{ csrf_token }}", 'like': like}
                })
                .done(function (response) {
                    if(response.success){
                        var votes = $(element).closest('.votes')
                        $(votes).find('.like_count').text(response.likes)
                        $(votes).find('.dislike_count').text(response.dislikes)                        
                    }else{
                        message(response.msg, color)
                    }
                })          
            });
            
            $(".bookmark-btn").click(function(e){
                e.preventDefault();

                var element =$(this);
                var url = $(element).data("url");

                $.ajax({
                    type: "POST",
                    url: url,            
                    data: {csrfmiddlewaretoken: "{{ csrf_token }}"}
                })
                .done(function (response) {
                    if(response.success){
                        const icon = $(element).find("i")
                        if(response.bookmark){
                            $(icon).removeClass("icon-heart-o")
                            $(icon).addClass("icon-heart")
                        }else{
                            $(icon).removeClass("icon-heart")
                            $(icon).addClass("icon-heart-o")
                        }
                    }else{
                        message(response.msg, color)
                    }
                })          
            });

            $(".reply").click(function(e){
                e.preventDefault();

                var id = $(this).data("id");
                var html = $("#replyForm").children().clone();        
                $(html).find("[name='parent_id']").val(id);
                $(this).parent().next('.reply_div').append(html);
            });

        });
    </script>
{% endblock extra_scripts %}